export const LOADING_START = "LOADING_START";
export const FETCH_START = "FETCH_START";
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const DECREASE_FROM_CART = "DECREASE_FROM_CART";